service: simple-lambda-test
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-localstack
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  logRetentionInDays: 3
  stage: dev
  versionFunctions: false
  environment:
    ENV_VAR_INSIDE_LAMBDA: ${self:custom.envVar}
package:
  exclude:
    - node_modules/**

functions:
  hello:
    handler: hello.handler
    events:
      - http: GET /
          
custom:
  envVar: ${env:ENV_VAR_WHEN_RUNNING_SLS,"default-value"}
  localstack:
    stages: 
      - local
    host: http://nuc
  serverless-offline:
    port: 4000